  CREATE OR REPLACE TRIGGER "SYSTEM"."TRG_UPD_WAREHOUSE" 
AFTER INSERT OR UPDATE OF LINE_ITEM_ID,QUANTITY,ORDR_ID,ITEM_DESC ON LINE_ITEM_T 
BEGIN
  UPDATE WAREHOUSE_T WT
  SET WT.QUANTITY_AVL=(SELECT WT.QUANTITY_AVL-LT.QUANTITY FROM LINE_ITEM_T LT WHERE LT.ITEM_DESC=WT.ITEM_NAME)
  WHERE EXISTS (SELECT NULL FROM LINE_ITEM_T LT WHERE LT.ITEM_DESC=WT.ITEM_NAME);
END;
/
ALTER TRIGGER "SYSTEM"."TRIGGER1" ENABLE;


--------------------------------------------------------
--  DDL for Table CUSTOMER_T
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER_T" 
   (	"CUST_ID" NUMBER(11,0), 
	"CUST_NAME" VARCHAR2(50 BYTE), 
	"CUST_ADDRESS" VARCHAR2(100 BYTE), 
	"CUST_PHONE" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMER_T
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER_T (CUST_ID,CUST_NAME,CUST_ADDRESS,CUST_PHONE) values (10000000001,'Jose Stockham','Getzville','716-903-1111');
Insert into SYSTEM.CUSTOMER_T (CUST_ID,CUST_NAME,CUST_ADDRESS,CUST_PHONE) values (10000000002,'Rozella Ostrosky','Amherst','716-903-1112');
Insert into SYSTEM.CUSTOMER_T (CUST_ID,CUST_NAME,CUST_ADDRESS,CUST_PHONE) values (10000000003,'Valentine Gillian','Cheektowaga','716-903-1113');
Insert into SYSTEM.CUSTOMER_T (CUST_ID,CUST_NAME,CUST_ADDRESS,CUST_PHONE) values (10000000004,'Jina Briddick','Elmwood','716-903-1114');
Insert into SYSTEM.CUSTOMER_T (CUST_ID,CUST_NAME,CUST_ADDRESS,CUST_PHONE) values (10000000005,'Roxane Campain','Amherst','716-903-1115');
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CUSTOMER_PK" ON "SYSTEM"."CUSTOMER_T" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_T
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER_T" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CUSTOMER_T" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CUSTOMER_T" MODIFY ("CUST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CUSTOMER_T" MODIFY ("CUST_ADDRESS" NOT NULL ENABLE);

  
  --------------------------------------------------------------------------
  
  --------------------------------------------------------
--  DDL for Table FARMER_T
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FARMER_T" 
   (	"FARMER_ID" NUMBER(11,0), 
	"FARMER_NAME" VARCHAR2(50 BYTE), 
	"FARMER_ADDRESS" VARCHAR2(100 BYTE), 
	"FARMER_PHONE" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.FARMER_T
SET DEFINE OFF;
Insert into SYSTEM.FARMER_T (FARMER_ID,FARMER_NAME,FARMER_ADDRESS,FARMER_PHONE) values (1001,'James Button','Gotham','716-903-1216');
Insert into SYSTEM.FARMER_T (FARMER_ID,FARMER_NAME,FARMER_ADDRESS,FARMER_PHONE) values (1002,'Joseph Darakjy','Smallville','716-903-1217');
Insert into SYSTEM.FARMER_T (FARMER_ID,FARMER_NAME,FARMER_ADDRESS,FARMER_PHONE) values (1003,'Leonard Paprocki','Amherst','716-903-1218');
Insert into SYSTEM.FARMER_T (FARMER_ID,FARMER_NAME,FARMER_ADDRESS,FARMER_PHONE) values (1004,'Don Foller','Getzville','716-903-1219');
Insert into SYSTEM.FARMER_T (FARMER_ID,FARMER_NAME,FARMER_ADDRESS,FARMER_PHONE) values (1005,'Simon Morasca','Buffalo','716-904-1220');
--------------------------------------------------------
--  DDL for Index FARMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FARMER_PK" ON "SYSTEM"."FARMER_T" ("FARMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FARMER_T
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FARMER_T" ADD CONSTRAINT "FARMER_PK" PRIMARY KEY ("FARMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."FARMER_T" MODIFY ("FARMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FARMER_T" MODIFY ("FARMER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FARMER_T" MODIFY ("FARMER_ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger FARMER_T_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."FARMER_T_TRG" 
BEFORE INSERT ON FARMER_T 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FARMER_ID IS NULL THEN
      SELECT FARMER_T_SEQ.NEXTVAL INTO :NEW.FARMER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."FARMER_T_TRG" ENABLE;
