CREATE TABLE Farmer_T
(
Farmer_ID NUMBER(11,0) NOT  NULL,
Farmer_Name VARCHAR2(50) NOT NULL,
Farmer_Address VARCHAR2(100) NOT NULL,
Farmer_Phone  VARCHAR2(30) ,
CONSTRAINT Farmer_PK PRIMARY KEY (Farmer_ID)
);

CREATE TABLE Stock_T
(
Stock_ID NUMBER(11,0) NOT  NULL,
Stock_Name VARCHAR2(30) NOT NULL,
Quantity NUMBER(20,0),
Stock_Dt Date ,
Farmer_ID NUMBER(11,0) NOT NULL,
CONSTRAINT Stock_PK PRIMARY KEY (Stock_ID),
CONSTRAINT Stock_FK FOREIGN KEY (Farmer_ID) REFERENCES Farmer_T(FARMER_ID)
 );
 
 
 
CREATE TABLE Contract_T
(
Contract_ID NUMBER(11,0) NOT NULL,
Strt_Dt Date NOT NULL,
End_Dt Date NOT NULL,
Farmer_ID NUMBER(11,0) NOT NULL,
Stock_Dt Date,
CONSTRAINT Contract_PK PRIMARY KEY (Contract_ID),
CONSTRAINT Farmer_Cntrct_FK FOREIGN KEY (Farmer_ID) REFERENCES Farmer_T(Farmer_ID)
);
 
 
CREATE TABLE Customer_T
(
Cust_ID NUMBER(11,0) NOT  NULL,
Cust_Name  VARCHAR2(50)  NOT NULL,
Cust_Address  VARCHAR2(100)  NOT NULL,
Cust_Phone  VARCHAR2(30) ,
CONSTRAINT Customer_PK PRIMARY KEY (Cust_ID)
);

CREATE TABLE Warehouse_T
(
Invntry_ID NUMBER(11,0) NOT  NULL,
Item_Name VARCHAR2(30) NOT NULL,
Quantity_Avl  NUMBER (10,0) NOT NULL,
CONSTRAINT Warehouse_PK PRIMARY KEY (Invntry_ID)
);



CREATE TABLE Shipment_T
(
Shipment_ID NUMBER(11,0) NOT  NULL,
Shipping_Dt DATE NOT NULL,
Ordr_ID NUMBER(11,0) NOT NULL,
CONSTRAINT Shipping_PK PRIMARY KEY (Shipment_ID)
);


CREATE TABLE Order_T
(
Ordr_ID NUMBER(11,0) NOT  NULL,
Ordr_Dt Date  NOT NULL,
Ordr_Dlvry_Dt Date NOT NULL,
Item_Desc  VARCHAR2 (25) NOT NULL ,
Ordr_Amt NUMBER (5,2),
Cust_ID NUMBER(11,0) NOT  NULL,
Shipment_ID NUMBER(11,0) NOT  NULL,
CONSTRAINT Order_PK PRIMARY KEY (Ordr_ID),
CONSTRAINT Cust_Ord_FK FOREIGN KEY (Cust_ID) REFERENCES Customer_T (Cust_ID),
CONSTRAINT Ord_Ship_FK FOREIGN KEY (Shipment_ID) REFERENCES Shipment_T (Shipment_ID)
);

CREATE TABLE LINE_ITEM_T
(
LINE_ITEM_ID NUMBER(11,0) NOT NULL,
ITEM_DESC VARCHAR2(50),
QUANTITY NUMBER(5,0),
ORDR_ID NUMBER(11,0) NOT  NULL,
CONSTRAINT ORD_LINE_FK FOREIGN KEY (ORDR_ID) REFERENCES ORDER_T(ORDR_ID)
);


CREATE TABLE Invoice_T
(
Invoice_ID NUMBER(11,0) NOT  NULL,
Tax_ID NUMBER(11,0) NOT  NULL,
Item VARCHAR2(30) NOT NULL,
Quantity NUMBER (10,0) NOT NULL,
Bill_Amt Number(5,2),
Tax_Amt Number(5,2),
Total_Amt NUMBER (5,2),
Shipment_ID NUMBER(11,0) NOT  NULL,
CONSTRAINT Invoice_PK PRIMARY KEY (Invoice_ID),
CONSTRAINT Invoice_FK FOREIGN KEY (Shipment_ID) REFERENCES Shipment_T (Shipment_ID)
);
  
 
CREATE TABLE Payment_T
(
Payment_ID NUMBER(11,0) NOT NULL,
Payment_Amt NUMBER(5,2) NOT NULL,
Payment_Mode VARCHAR2(10) NOT NULL,
Trnsctn_Dt DATE NOT NULL,
Invoice_ID NUMBER(11,0) NOT  NULL,
CONSTRAINT Payment_PK PRIMARY KEY (Payment_ID),
CONSTRAINT Payment_FK FOREIGN KEY (Invoice_ID) REFERENCES Invoice_T (Invoice_ID)
);
 
 


 
